version: '3.8'

services:
  oracle-client:
    build:
      context: .
      dockerfile: Dockerfile.instant-client
    container_name: oracle-client
    hostname: oracle-client
    environment:
      - ORACLE_HOME=/opt/oracle/instantclient_21_12
      - LD_LIBRARY_PATH=/opt/oracle/instantclient_21_12
      - PATH=$PATH:/opt/oracle/instantclient_21_12
      - NLS_LANG=AMERICAN_AMERICA.UTF8
    volumes:
      - ./sql:/sql:ro
    working_dir: /sql
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  default:
    name: oracle-network